### PR TITLE
project: Actually fix issues described in #146

### PR DESCRIPTION
**Pull request by Xaymar**
### Description
Fixes most/all issues described in #146, which seem to be Clang exclusive.

### Related Issues
- #146 Various compiling issues on Clang

### CODE REVIEW

**Comment by yurivict** [comment]
Build fails with this patch with a different error message:
http://beefy17.nyi.freebsd.org/data/head-i386-default/p532060_s360085/logs/obs-streamfx-0.8.0.b1_1.log (IPv6 URL)

```
/wrkdirs/usr/ports/multimedia/obs-streamfx/work/obs-StreamFX-0.8.0b1/source/util-profiler.cpp:122:8: error: no matching function for call to 'is_equal'
                        if (is_equal(kv_pct, percentile, 0.00005) || (kv_pct > percentile)) {
                            ^~~~~~~~
/wrkdirs/usr/ports/multimedia/obs-streamfx/work/obs-StreamFX-0.8.0b1/source/util-profiler.cpp:97:13: note: candidate template ignored: deduced conflicting types for parameter 'T' ('long double' vs. 'double')
inline bool is_equal(T a, T b, T c)
            ^
/wrkdirs/usr/ports/multimedia/obs-streamfx/work/obs-StreamFX-0.8.0b1/source/util-profiler.cpp:139:8: error: no matching function for call to 'is_equal'
                        if (is_equal(percentile, percentile_now, 0.0005)
                            ^~~~~~~~
/wrkdirs/usr/ports/multimedia/obs-streamfx/work/obs-StreamFX-0.8.0b1/source/util-profiler.cpp:97:13: note: candidate template ignored: deduced conflicting types for parameter 'T' ('long double' vs. 'double')
inline bool is_equal(T a, T b, T c)
            ^
```

**Comment by Xaymar** [comment]
Hmm, that seems to be a FLT_EVAL_METHOD issue where the compiler defaults to FLT_EVAL_METHOD=2 instead of 0. Will have to add a define for it to ensure identical behavior to the expected types.

**Comment by Xaymar** [comment]
Pushed another fix, which should hopefully fix the util-profiler issues.

**Comment by Xaymar** [comment]
Tried to add clang-10 building, but ultimately failed at that for an unknown reason none of the commands actually did anything. So far though I can confirm it working fine with clang-8 and clang-9.

**Comment by Xaymar** [comment]
Can't find any new issues with clang-10, as evidenced by CI compiling fine with it.

**Pull request merged**
