### PR TITLE
Adding some new cool shaders

### PR DESCRIPTION
**Pull request by DarkReaper231**

### CODE REVIEW

**Comment by Xaymar** [comment]
Please actually fill out the template. As it is, I can't merge or rebase this at all.

**Comment by DarkReaper231** [comment]
> 
> 
> Please actually fill out the template. As it is, I can't merge or rebase this at all.

Okay, I actually didn't do any PRs in a long time so I'll have to look into that more.

**Comment by Xaymar** [comment]
There has been no activity for 24 days after asking for changes. Closing as unmaintained.

**Comment by DarkReaper231** [comment]
I don't know how to fill out templates

**Comment by Xaymar** [comment]
> I don't know how to fill out templates.

Just... edit your original post and actually read what it says?

**Comment by DarkReaper231** [comment]
Am I supposed to remove those lines? 
// License Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License
// Contact the author for other licensing options

**Comment by DarkReaper231** [comment]
Or does it have to contain all the defines and stuff like here? https://github.com/Xaymar/obs-StreamFX/blob/master/data/examples/shaders/source/shadertoy-template.effect

**Comment by Xaymar** [comment]
Are you not aware of how you actually opened this PR? You edit the first _post_ not the content.

**Comment by DarkReaper231** [comment]
I noticed the PR template text when I made new PR. Howerver I already edited all the shaders so they all use the shadertoy-template.effect structure. And the build in new PR didn't failed like this one so I guess the new PR is better then this one?

**Comment by DarkReaper231** [comment]
Also I added one more effect to the new PR so that's bonus

**Comment by Xaymar** [comment]
I was not talking about shadertoy-template.effect, that was added by someone else. I was talking about the post template, which is still in this PR's original post - like I asked you multiple times. You did fill it out in the new PR though, so let's move discussion over to it.

**Comment by DarkReaper231** [comment]
okay

**Pull request closed without merging**
